### ISSUE TITLE
Bitrate independens?

### ISSUE THREAD

**Issue by MrSVCD** [aarossig/datvideo#1]
I am just checking if datvideo is sample rate/number of channel/sample bit size independent so I can use it with CDs (one of cheapest way to test datvideo, at least for me) and other digital pcm media.

**Comment by aarossig** [comment]
Actually, the datvideo tool is totally unaware of the data stream that it is encoding. You could pass just about anything through it. The first test I did was with a JPEG before moving onto h265 video.
